[project]
# The name of your game's executable. This should only contain a-z, A-Z, 0-9, _ or -.
name = "NewMay"
# The game's title. This will show up in the tile bar of your executable.
title = "New May"
version = "0.1.0"
authors = ["Rosareven <dev@rovingamer.com>"]
icon = "metadata/icon.png"
compile_ruby = false

[dragonruby]
version = "3.15"
edition = "standard"

[dependencies]
zif = "2.0.0-rc.2"

[itch]
# The Project URL you set when you created the game on Itch.io. https://my-username.itch.io/my-game.
# This will also be the name of your build files, so fill it out even if you aren't uploading to Itch.io.
url = "https://rosareven.itch.io/"
# Your username on Itch.io.
username = "rosareven"
